name: Node CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: node:18

    steps:
      - uses: actions/checkout@v1
      - name: Install npm
        run: |
          npm install
      - name: Run linter
        run: |
          npm ci
          npm run lint
        env:
          CI: true
          NODE_ENV: test
      - name: Build the project
        run: |
          npm run build
        env:
          CI: true
          MORALIS_API_KEY: UOcmzVX7SBgwH1UsNfGuXon78eVB2LKrBVBm5cbMzad3rnVPyPWOra77qYsWBdSP
      - uses: actions/upload-artifact@v3
        with:
          name: build
          path: build
